---
- name: Déployer un serveur LAMP et WordPress
  hosts: vm-web
  vars_files:
    - wp_secrets.yaml
  become: true
  tasks:

    - name: Installer Apache, PHP et modules nécessaires
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - php-xml
          - php-curl
          - php-zip
        state: present

    - name: Désactiver le site par défaut
      command: a2dissite 000-default.conf
      notify:
        - Restart Apache

    - name: Démarrer et activer Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Télécharger WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extraire WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        copy: no

    - name: Définir les permissions pour le dossier WordPress
      file:
        path: /var/www/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configurer Apache pour WordPress
      blockinfile:
        path: /etc/apache2/sites-available/wordpress.conf
        create: yes
        block: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/wordpress
              ServerName 172.20.10.9

              <Directory /var/www/wordpress>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Activer le site WordPress
      command: a2ensite wordpress.conf
      notify:
        - Restart Apache

    - name: Activer les modules nécessaires
      apache2_module:
        name: rewrite
        state: present

    - name: Configurer WordPress
      template:
        src: wp-config.php.j2 // Créer un fichier templates/wp-config.php.j2 comme celui-ci : https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: '0644'

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

